### ISSUE TITLE
Can't run geodeo - missing scripts

### ISSUE THREAD

**Issue by flsimoes** [punkish/geodeo#1]
I'm probably doing it wrong, but I couldn't get geodeo to run. It says the script is missing.

![image](https://github.com/user-attachments/assets/5aec28e7-c743-4796-8470-70d213dfd2ff)
![image](https://github.com/user-attachments/assets/1b8e4b9d-4d14-4edd-beda-8f45e9e2b704)

**Comment by punkish** [comment]
heh, you are not really supposed to install geodeo. It is just something I created to use on Ocellus and other projects. That said, if you really want to install and test geodeo, you need to get the data as well. And, you have to start the server with `bun dev`. I should perhaps add more clear instructions for those wanting to install and run it themselves.

**Comment by punkish** [comment]
The db(s) are rather large, and including them here is beyond the current scope I have in mind for this project. Perhaps I should create a small db for demo purposes and include it in the repo here. When I do that, I will let you know. But, all that will be of interest to you only if you are interested in developing or running this program yourself. My guess is, "no". Let me know if my assumptions are wrong.
